name: test1 ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]
        project: ['test1', 'test2', 'test3', 'test4', 'test5', 'test6', 'test7']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build
        run: cd ${{ matrix.project }} && dotnet build
      - name: Test
        run: cd ${{ matrix.project }} && dotnet test 
