name: kind of continuous integration

on: [push]

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "::set-output name=path_matrix::$(find . -type f -name '*.csproj' | sed -r 's|/[^/]+$||' | jq --raw-input . | jq --slurp . | tr -d '\n')"
    outputs:
      path_matrix: ${{ steps.set-matrix.outputs.path_matrix }}

  build:
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      matrix:
        path: ${{ fromJson(needs.build-matrix.outputs.path_matrix) }}
    steps:
        - run: echo ${{ needs.build-matrix.outputs.path_matrix }}
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Build
        run: cd ${{ matrix.path }} && dotnet build
      - name: Test
        run: cd ${{ matrix.path }} && dotnet test
